dist: focal
language: cpp
before_install: source travis/setup.sh
script:
  - export PKG_CONFIG_PATH="travis/pc"
  - make env
  - make
compiler:
  - g++
  - clang++
notifications:
  email: false
  irc:
    channels:
      - "irc.atw-inter.net#udpgame"
    use_notice: true
    skip_join: true
    template: "%{message} %{build_url}"
    on_success: change
    on_failure: change
