build:
  project: vsprojects\udpgame.sln

branches:
  except:
    - /.*-osx/

configuration:
  - Release

platform:
  - x64

notifications:
  webhooks:
    url: http://soulaim.dy.fi:6776/appveyor
    events: [build_success, build_failure]

artifacts:
  - path: udpgame.zip
