// Generated by the protocol buffer compiler.  DO NOT EDIT!

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "common/proto/udpgame.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* AMessage_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  AMessage_reflection_ = NULL;
const ::google::protobuf::Descriptor* WorldState_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  WorldState_reflection_ = NULL;
const ::google::protobuf::Descriptor* Object_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Object_reflection_ = NULL;
const ::google::protobuf::Descriptor* ClientInput_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  ClientInput_reflection_ = NULL;
const ::google::protobuf::EnumDescriptor* Type_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_common_2fproto_2fudpgame_2eproto() {
  protobuf_AddDesc_common_2fproto_2fudpgame_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "common/proto/udpgame.proto");
  GOOGLE_CHECK(file != NULL);
  AMessage_descriptor_ = file->message_type(0);
  static const int AMessage_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AMessage, type_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AMessage, world_state_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AMessage, input_),
  };
  AMessage_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      AMessage_descriptor_,
      AMessage::default_instance_,
      AMessage_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AMessage, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AMessage, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(AMessage));
  WorldState_descriptor_ = file->message_type(1);
  static const int WorldState_offsets_[5] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(WorldState, tick_number_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(WorldState, owned_id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(WorldState, client_mode_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(WorldState, object_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(WorldState, grid_),
  };
  WorldState_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      WorldState_descriptor_,
      WorldState::default_instance_,
      WorldState_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(WorldState, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(WorldState, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(WorldState));
  Object_descriptor_ = file->message_type(2);
  static const int Object_offsets_[9] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Object, id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Object, x_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Object, y_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Object, z_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Object, horizontal_angle_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Object, vertical_angle_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Object, dim_x_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Object, dim_y_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Object, dim_z_),
  };
  Object_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      Object_descriptor_,
      Object::default_instance_,
      Object_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Object, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Object, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(Object));
  ClientInput_descriptor_ = file->message_type(3);
  static const int ClientInput_offsets_[4] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ClientInput, tick_number_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ClientInput, actions_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ClientInput, horizontal_delta_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ClientInput, verical_delta_),
  };
  ClientInput_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      ClientInput_descriptor_,
      ClientInput::default_instance_,
      ClientInput_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ClientInput, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ClientInput, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(ClientInput));
  Type_descriptor_ = file->enum_type(0);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_common_2fproto_2fudpgame_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    AMessage_descriptor_, &AMessage::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    WorldState_descriptor_, &WorldState::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    Object_descriptor_, &Object::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    ClientInput_descriptor_, &ClientInput::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_common_2fproto_2fudpgame_2eproto() {
  delete AMessage::default_instance_;
  delete AMessage_reflection_;
  delete WorldState::default_instance_;
  delete WorldState_reflection_;
  delete Object::default_instance_;
  delete Object_reflection_;
  delete ClientInput::default_instance_;
  delete ClientInput_reflection_;
}

void protobuf_AddDesc_common_2fproto_2fudpgame_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\032common/proto/udpgame.proto\"^\n\010AMessage"
    "\022\023\n\004type\030\001 \002(\0162\005.Type\022 \n\013world_state\030\002 \001"
    "(\0132\013.WorldState\022\033\n\005input\030\003 \001(\0132\014.ClientI"
    "nput\"o\n\nWorldState\022\023\n\013tick_number\030\001 \002(\007\022"
    "\020\n\010owned_id\030\002 \002(\007\022\023\n\013client_mode\030\003 \002(\007\022\027"
    "\n\006object\030\004 \003(\0132\007.Object\022\014\n\004grid\030\005 \002(\014\"\224\001"
    "\n\006Object\022\n\n\002id\030\001 \002(\007\022\t\n\001x\030\002 \002(\002\022\t\n\001y\030\003 \002"
    "(\002\022\t\n\001z\030\004 \002(\002\022\030\n\020horizontal_angle\030\005 \002(\002\022"
    "\026\n\016vertical_angle\030\006 \002(\002\022\r\n\005dim_x\030\007 \002(\002\022\r"
    "\n\005dim_y\030\010 \002(\002\022\r\n\005dim_z\030\t \002(\002\"d\n\013ClientIn"
    "put\022\023\n\013tick_number\030\001 \002(\007\022\017\n\007actions\030\002 \002("
    "\007\022\030\n\020horizontal_delta\030\003 \002(\002\022\025\n\rverical_d"
    "elta\030\004 \002(\002*)\n\004Type\022\017\n\013WORLD_STATE\020\001\022\020\n\014C"
    "LIENT_INPUT\020\002", 533);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "common/proto/udpgame.proto", &protobuf_RegisterTypes);
  AMessage::default_instance_ = new AMessage();
  WorldState::default_instance_ = new WorldState();
  Object::default_instance_ = new Object();
  ClientInput::default_instance_ = new ClientInput();
  AMessage::default_instance_->InitAsDefaultInstance();
  WorldState::default_instance_->InitAsDefaultInstance();
  Object::default_instance_->InitAsDefaultInstance();
  ClientInput::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_common_2fproto_2fudpgame_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_common_2fproto_2fudpgame_2eproto {
  StaticDescriptorInitializer_common_2fproto_2fudpgame_2eproto() {
    protobuf_AddDesc_common_2fproto_2fudpgame_2eproto();
  }
} static_descriptor_initializer_common_2fproto_2fudpgame_2eproto_;

const ::google::protobuf::EnumDescriptor* Type_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Type_descriptor_;
}
bool Type_IsValid(int value) {
  switch(value) {
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}


// ===================================================================

#ifndef _MSC_VER
const int AMessage::kTypeFieldNumber;
const int AMessage::kWorldStateFieldNumber;
const int AMessage::kInputFieldNumber;
#endif  // !_MSC_VER

AMessage::AMessage()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void AMessage::InitAsDefaultInstance() {
  world_state_ = const_cast< ::WorldState*>(&::WorldState::default_instance());
  input_ = const_cast< ::ClientInput*>(&::ClientInput::default_instance());
}

AMessage::AMessage(const AMessage& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void AMessage::SharedCtor() {
  _cached_size_ = 0;
  type_ = 1;
  world_state_ = NULL;
  input_ = NULL;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

AMessage::~AMessage() {
  SharedDtor();
}

void AMessage::SharedDtor() {
  if (this != default_instance_) {
    delete world_state_;
    delete input_;
  }
}

void AMessage::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* AMessage::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return AMessage_descriptor_;
}

const AMessage& AMessage::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_common_2fproto_2fudpgame_2eproto();  return *default_instance_;
}

AMessage* AMessage::default_instance_ = NULL;

AMessage* AMessage::New() const {
  return new AMessage;
}

void AMessage::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    type_ = 1;
    if (has_world_state()) {
      if (world_state_ != NULL) world_state_->::WorldState::Clear();
    }
    if (has_input()) {
      if (input_ != NULL) input_->::ClientInput::Clear();
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool AMessage::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required .Type type = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (Type_IsValid(value)) {
            set_type(static_cast< Type >(value));
          } else {
            mutable_unknown_fields()->AddVarint(1, value);
          }
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_world_state;
        break;
      }
      
      // optional .WorldState world_state = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_world_state:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_world_state()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(26)) goto parse_input;
        break;
      }
      
      // optional .ClientInput input = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_input:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_input()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void AMessage::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required .Type type = 1;
  if (has_type()) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->type(), output);
  }
  
  // optional .WorldState world_state = 2;
  if (has_world_state()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->world_state(), output);
  }
  
  // optional .ClientInput input = 3;
  if (has_input()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, this->input(), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* AMessage::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required .Type type = 1;
  if (has_type()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      1, this->type(), target);
  }
  
  // optional .WorldState world_state = 2;
  if (has_world_state()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        2, this->world_state(), target);
  }
  
  // optional .ClientInput input = 3;
  if (has_input()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        3, this->input(), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int AMessage::ByteSize() const {
  int total_size = 0;
  
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required .Type type = 1;
    if (has_type()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::EnumSize(this->type());
    }
    
    // optional .WorldState world_state = 2;
    if (has_world_state()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->world_state());
    }
    
    // optional .ClientInput input = 3;
    if (has_input()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->input());
    }
    
  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void AMessage::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const AMessage* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const AMessage*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void AMessage::MergeFrom(const AMessage& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_type()) {
      set_type(from.type());
    }
    if (from.has_world_state()) {
      mutable_world_state()->::WorldState::MergeFrom(from.world_state());
    }
    if (from.has_input()) {
      mutable_input()->::ClientInput::MergeFrom(from.input());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void AMessage::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void AMessage::CopyFrom(const AMessage& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool AMessage::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;
  
  if (has_world_state()) {
    if (!this->world_state().IsInitialized()) return false;
  }
  if (has_input()) {
    if (!this->input().IsInitialized()) return false;
  }
  return true;
}

void AMessage::Swap(AMessage* other) {
  if (other != this) {
    std::swap(type_, other->type_);
    std::swap(world_state_, other->world_state_);
    std::swap(input_, other->input_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata AMessage::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = AMessage_descriptor_;
  metadata.reflection = AMessage_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int WorldState::kTickNumberFieldNumber;
const int WorldState::kOwnedIdFieldNumber;
const int WorldState::kClientModeFieldNumber;
const int WorldState::kObjectFieldNumber;
const int WorldState::kGridFieldNumber;
#endif  // !_MSC_VER

WorldState::WorldState()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void WorldState::InitAsDefaultInstance() {
}

WorldState::WorldState(const WorldState& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void WorldState::SharedCtor() {
  _cached_size_ = 0;
  tick_number_ = 0u;
  owned_id_ = 0u;
  client_mode_ = 0u;
  grid_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

WorldState::~WorldState() {
  SharedDtor();
}

void WorldState::SharedDtor() {
  if (grid_ != &::google::protobuf::internal::kEmptyString) {
    delete grid_;
  }
  if (this != default_instance_) {
  }
}

void WorldState::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* WorldState::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return WorldState_descriptor_;
}

const WorldState& WorldState::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_common_2fproto_2fudpgame_2eproto();  return *default_instance_;
}

WorldState* WorldState::default_instance_ = NULL;

WorldState* WorldState::New() const {
  return new WorldState;
}

void WorldState::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    tick_number_ = 0u;
    owned_id_ = 0u;
    client_mode_ = 0u;
    if (has_grid()) {
      if (grid_ != &::google::protobuf::internal::kEmptyString) {
        grid_->clear();
      }
    }
  }
  object_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool WorldState::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required fixed32 tick_number = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED32) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_FIXED32>(
                 input, &tick_number_)));
          set_has_tick_number();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(21)) goto parse_owned_id;
        break;
      }
      
      // required fixed32 owned_id = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED32) {
         parse_owned_id:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_FIXED32>(
                 input, &owned_id_)));
          set_has_owned_id();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(29)) goto parse_client_mode;
        break;
      }
      
      // required fixed32 client_mode = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED32) {
         parse_client_mode:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_FIXED32>(
                 input, &client_mode_)));
          set_has_client_mode();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(34)) goto parse_object;
        break;
      }
      
      // repeated .Object object = 4;
      case 4: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_object:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_object()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(34)) goto parse_object;
        if (input->ExpectTag(42)) goto parse_grid;
        break;
      }
      
      // required bytes grid = 5;
      case 5: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_grid:
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_grid()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void WorldState::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required fixed32 tick_number = 1;
  if (has_tick_number()) {
    ::google::protobuf::internal::WireFormatLite::WriteFixed32(1, this->tick_number(), output);
  }
  
  // required fixed32 owned_id = 2;
  if (has_owned_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteFixed32(2, this->owned_id(), output);
  }
  
  // required fixed32 client_mode = 3;
  if (has_client_mode()) {
    ::google::protobuf::internal::WireFormatLite::WriteFixed32(3, this->client_mode(), output);
  }
  
  // repeated .Object object = 4;
  for (int i = 0; i < this->object_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      4, this->object(i), output);
  }
  
  // required bytes grid = 5;
  if (has_grid()) {
    ::google::protobuf::internal::WireFormatLite::WriteBytes(
      5, this->grid(), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* WorldState::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required fixed32 tick_number = 1;
  if (has_tick_number()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFixed32ToArray(1, this->tick_number(), target);
  }
  
  // required fixed32 owned_id = 2;
  if (has_owned_id()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFixed32ToArray(2, this->owned_id(), target);
  }
  
  // required fixed32 client_mode = 3;
  if (has_client_mode()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFixed32ToArray(3, this->client_mode(), target);
  }
  
  // repeated .Object object = 4;
  for (int i = 0; i < this->object_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        4, this->object(i), target);
  }
  
  // required bytes grid = 5;
  if (has_grid()) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        5, this->grid(), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int WorldState::ByteSize() const {
  int total_size = 0;
  
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required fixed32 tick_number = 1;
    if (has_tick_number()) {
      total_size += 1 + 4;
    }
    
    // required fixed32 owned_id = 2;
    if (has_owned_id()) {
      total_size += 1 + 4;
    }
    
    // required fixed32 client_mode = 3;
    if (has_client_mode()) {
      total_size += 1 + 4;
    }
    
    // required bytes grid = 5;
    if (has_grid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::BytesSize(
          this->grid());
    }
    
  }
  // repeated .Object object = 4;
  total_size += 1 * this->object_size();
  for (int i = 0; i < this->object_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->object(i));
  }
  
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void WorldState::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const WorldState* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const WorldState*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void WorldState::MergeFrom(const WorldState& from) {
  GOOGLE_CHECK_NE(&from, this);
  object_.MergeFrom(from.object_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_tick_number()) {
      set_tick_number(from.tick_number());
    }
    if (from.has_owned_id()) {
      set_owned_id(from.owned_id());
    }
    if (from.has_client_mode()) {
      set_client_mode(from.client_mode());
    }
    if (from.has_grid()) {
      set_grid(from.grid());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void WorldState::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void WorldState::CopyFrom(const WorldState& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool WorldState::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000017) != 0x00000017) return false;
  
  for (int i = 0; i < object_size(); i++) {
    if (!this->object(i).IsInitialized()) return false;
  }
  return true;
}

void WorldState::Swap(WorldState* other) {
  if (other != this) {
    std::swap(tick_number_, other->tick_number_);
    std::swap(owned_id_, other->owned_id_);
    std::swap(client_mode_, other->client_mode_);
    object_.Swap(&other->object_);
    std::swap(grid_, other->grid_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata WorldState::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = WorldState_descriptor_;
  metadata.reflection = WorldState_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int Object::kIdFieldNumber;
const int Object::kXFieldNumber;
const int Object::kYFieldNumber;
const int Object::kZFieldNumber;
const int Object::kHorizontalAngleFieldNumber;
const int Object::kVerticalAngleFieldNumber;
const int Object::kDimXFieldNumber;
const int Object::kDimYFieldNumber;
const int Object::kDimZFieldNumber;
#endif  // !_MSC_VER

Object::Object()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void Object::InitAsDefaultInstance() {
}

Object::Object(const Object& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void Object::SharedCtor() {
  _cached_size_ = 0;
  id_ = 0u;
  x_ = 0;
  y_ = 0;
  z_ = 0;
  horizontal_angle_ = 0;
  vertical_angle_ = 0;
  dim_x_ = 0;
  dim_y_ = 0;
  dim_z_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

Object::~Object() {
  SharedDtor();
}

void Object::SharedDtor() {
  if (this != default_instance_) {
  }
}

void Object::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Object::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Object_descriptor_;
}

const Object& Object::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_common_2fproto_2fudpgame_2eproto();  return *default_instance_;
}

Object* Object::default_instance_ = NULL;

Object* Object::New() const {
  return new Object;
}

void Object::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    id_ = 0u;
    x_ = 0;
    y_ = 0;
    z_ = 0;
    horizontal_angle_ = 0;
    vertical_angle_ = 0;
    dim_x_ = 0;
    dim_y_ = 0;
  }
  if (_has_bits_[8 / 32] & (0xffu << (8 % 32))) {
    dim_z_ = 0;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool Object::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required fixed32 id = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED32) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_FIXED32>(
                 input, &id_)));
          set_has_id();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(21)) goto parse_x;
        break;
      }
      
      // required float x = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED32) {
         parse_x:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &x_)));
          set_has_x();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(29)) goto parse_y;
        break;
      }
      
      // required float y = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED32) {
         parse_y:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &y_)));
          set_has_y();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(37)) goto parse_z;
        break;
      }
      
      // required float z = 4;
      case 4: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED32) {
         parse_z:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &z_)));
          set_has_z();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(45)) goto parse_horizontal_angle;
        break;
      }
      
      // required float horizontal_angle = 5;
      case 5: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED32) {
         parse_horizontal_angle:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &horizontal_angle_)));
          set_has_horizontal_angle();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(53)) goto parse_vertical_angle;
        break;
      }
      
      // required float vertical_angle = 6;
      case 6: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED32) {
         parse_vertical_angle:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &vertical_angle_)));
          set_has_vertical_angle();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(61)) goto parse_dim_x;
        break;
      }
      
      // required float dim_x = 7;
      case 7: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED32) {
         parse_dim_x:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &dim_x_)));
          set_has_dim_x();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(69)) goto parse_dim_y;
        break;
      }
      
      // required float dim_y = 8;
      case 8: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED32) {
         parse_dim_y:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &dim_y_)));
          set_has_dim_y();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(77)) goto parse_dim_z;
        break;
      }
      
      // required float dim_z = 9;
      case 9: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED32) {
         parse_dim_z:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &dim_z_)));
          set_has_dim_z();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void Object::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required fixed32 id = 1;
  if (has_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteFixed32(1, this->id(), output);
  }
  
  // required float x = 2;
  if (has_x()) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(2, this->x(), output);
  }
  
  // required float y = 3;
  if (has_y()) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(3, this->y(), output);
  }
  
  // required float z = 4;
  if (has_z()) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(4, this->z(), output);
  }
  
  // required float horizontal_angle = 5;
  if (has_horizontal_angle()) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(5, this->horizontal_angle(), output);
  }
  
  // required float vertical_angle = 6;
  if (has_vertical_angle()) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(6, this->vertical_angle(), output);
  }
  
  // required float dim_x = 7;
  if (has_dim_x()) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(7, this->dim_x(), output);
  }
  
  // required float dim_y = 8;
  if (has_dim_y()) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(8, this->dim_y(), output);
  }
  
  // required float dim_z = 9;
  if (has_dim_z()) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(9, this->dim_z(), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* Object::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required fixed32 id = 1;
  if (has_id()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFixed32ToArray(1, this->id(), target);
  }
  
  // required float x = 2;
  if (has_x()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(2, this->x(), target);
  }
  
  // required float y = 3;
  if (has_y()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(3, this->y(), target);
  }
  
  // required float z = 4;
  if (has_z()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(4, this->z(), target);
  }
  
  // required float horizontal_angle = 5;
  if (has_horizontal_angle()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(5, this->horizontal_angle(), target);
  }
  
  // required float vertical_angle = 6;
  if (has_vertical_angle()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(6, this->vertical_angle(), target);
  }
  
  // required float dim_x = 7;
  if (has_dim_x()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(7, this->dim_x(), target);
  }
  
  // required float dim_y = 8;
  if (has_dim_y()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(8, this->dim_y(), target);
  }
  
  // required float dim_z = 9;
  if (has_dim_z()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(9, this->dim_z(), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int Object::ByteSize() const {
  int total_size = 0;
  
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required fixed32 id = 1;
    if (has_id()) {
      total_size += 1 + 4;
    }
    
    // required float x = 2;
    if (has_x()) {
      total_size += 1 + 4;
    }
    
    // required float y = 3;
    if (has_y()) {
      total_size += 1 + 4;
    }
    
    // required float z = 4;
    if (has_z()) {
      total_size += 1 + 4;
    }
    
    // required float horizontal_angle = 5;
    if (has_horizontal_angle()) {
      total_size += 1 + 4;
    }
    
    // required float vertical_angle = 6;
    if (has_vertical_angle()) {
      total_size += 1 + 4;
    }
    
    // required float dim_x = 7;
    if (has_dim_x()) {
      total_size += 1 + 4;
    }
    
    // required float dim_y = 8;
    if (has_dim_y()) {
      total_size += 1 + 4;
    }
    
  }
  if (_has_bits_[8 / 32] & (0xffu << (8 % 32))) {
    // required float dim_z = 9;
    if (has_dim_z()) {
      total_size += 1 + 4;
    }
    
  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Object::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const Object* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const Object*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void Object::MergeFrom(const Object& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_id()) {
      set_id(from.id());
    }
    if (from.has_x()) {
      set_x(from.x());
    }
    if (from.has_y()) {
      set_y(from.y());
    }
    if (from.has_z()) {
      set_z(from.z());
    }
    if (from.has_horizontal_angle()) {
      set_horizontal_angle(from.horizontal_angle());
    }
    if (from.has_vertical_angle()) {
      set_vertical_angle(from.vertical_angle());
    }
    if (from.has_dim_x()) {
      set_dim_x(from.dim_x());
    }
    if (from.has_dim_y()) {
      set_dim_y(from.dim_y());
    }
  }
  if (from._has_bits_[8 / 32] & (0xffu << (8 % 32))) {
    if (from.has_dim_z()) {
      set_dim_z(from.dim_z());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void Object::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Object::CopyFrom(const Object& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Object::IsInitialized() const {
  if ((_has_bits_[0] & 0x000001ff) != 0x000001ff) return false;
  
  return true;
}

void Object::Swap(Object* other) {
  if (other != this) {
    std::swap(id_, other->id_);
    std::swap(x_, other->x_);
    std::swap(y_, other->y_);
    std::swap(z_, other->z_);
    std::swap(horizontal_angle_, other->horizontal_angle_);
    std::swap(vertical_angle_, other->vertical_angle_);
    std::swap(dim_x_, other->dim_x_);
    std::swap(dim_y_, other->dim_y_);
    std::swap(dim_z_, other->dim_z_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata Object::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Object_descriptor_;
  metadata.reflection = Object_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int ClientInput::kTickNumberFieldNumber;
const int ClientInput::kActionsFieldNumber;
const int ClientInput::kHorizontalDeltaFieldNumber;
const int ClientInput::kVericalDeltaFieldNumber;
#endif  // !_MSC_VER

ClientInput::ClientInput()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void ClientInput::InitAsDefaultInstance() {
}

ClientInput::ClientInput(const ClientInput& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void ClientInput::SharedCtor() {
  _cached_size_ = 0;
  tick_number_ = 0u;
  actions_ = 0u;
  horizontal_delta_ = 0;
  verical_delta_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

ClientInput::~ClientInput() {
  SharedDtor();
}

void ClientInput::SharedDtor() {
  if (this != default_instance_) {
  }
}

void ClientInput::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ClientInput::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ClientInput_descriptor_;
}

const ClientInput& ClientInput::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_common_2fproto_2fudpgame_2eproto();  return *default_instance_;
}

ClientInput* ClientInput::default_instance_ = NULL;

ClientInput* ClientInput::New() const {
  return new ClientInput;
}

void ClientInput::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    tick_number_ = 0u;
    actions_ = 0u;
    horizontal_delta_ = 0;
    verical_delta_ = 0;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool ClientInput::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required fixed32 tick_number = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED32) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_FIXED32>(
                 input, &tick_number_)));
          set_has_tick_number();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(21)) goto parse_actions;
        break;
      }
      
      // required fixed32 actions = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED32) {
         parse_actions:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_FIXED32>(
                 input, &actions_)));
          set_has_actions();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(29)) goto parse_horizontal_delta;
        break;
      }
      
      // required float horizontal_delta = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED32) {
         parse_horizontal_delta:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &horizontal_delta_)));
          set_has_horizontal_delta();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(37)) goto parse_verical_delta;
        break;
      }
      
      // required float verical_delta = 4;
      case 4: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED32) {
         parse_verical_delta:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &verical_delta_)));
          set_has_verical_delta();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void ClientInput::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required fixed32 tick_number = 1;
  if (has_tick_number()) {
    ::google::protobuf::internal::WireFormatLite::WriteFixed32(1, this->tick_number(), output);
  }
  
  // required fixed32 actions = 2;
  if (has_actions()) {
    ::google::protobuf::internal::WireFormatLite::WriteFixed32(2, this->actions(), output);
  }
  
  // required float horizontal_delta = 3;
  if (has_horizontal_delta()) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(3, this->horizontal_delta(), output);
  }
  
  // required float verical_delta = 4;
  if (has_verical_delta()) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(4, this->verical_delta(), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* ClientInput::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required fixed32 tick_number = 1;
  if (has_tick_number()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFixed32ToArray(1, this->tick_number(), target);
  }
  
  // required fixed32 actions = 2;
  if (has_actions()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFixed32ToArray(2, this->actions(), target);
  }
  
  // required float horizontal_delta = 3;
  if (has_horizontal_delta()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(3, this->horizontal_delta(), target);
  }
  
  // required float verical_delta = 4;
  if (has_verical_delta()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(4, this->verical_delta(), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int ClientInput::ByteSize() const {
  int total_size = 0;
  
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required fixed32 tick_number = 1;
    if (has_tick_number()) {
      total_size += 1 + 4;
    }
    
    // required fixed32 actions = 2;
    if (has_actions()) {
      total_size += 1 + 4;
    }
    
    // required float horizontal_delta = 3;
    if (has_horizontal_delta()) {
      total_size += 1 + 4;
    }
    
    // required float verical_delta = 4;
    if (has_verical_delta()) {
      total_size += 1 + 4;
    }
    
  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ClientInput::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const ClientInput* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const ClientInput*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void ClientInput::MergeFrom(const ClientInput& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_tick_number()) {
      set_tick_number(from.tick_number());
    }
    if (from.has_actions()) {
      set_actions(from.actions());
    }
    if (from.has_horizontal_delta()) {
      set_horizontal_delta(from.horizontal_delta());
    }
    if (from.has_verical_delta()) {
      set_verical_delta(from.verical_delta());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void ClientInput::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ClientInput::CopyFrom(const ClientInput& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ClientInput::IsInitialized() const {
  if ((_has_bits_[0] & 0x0000000f) != 0x0000000f) return false;
  
  return true;
}

void ClientInput::Swap(ClientInput* other) {
  if (other != this) {
    std::swap(tick_number_, other->tick_number_);
    std::swap(actions_, other->actions_);
    std::swap(horizontal_delta_, other->horizontal_delta_);
    std::swap(verical_delta_, other->verical_delta_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata ClientInput::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = ClientInput_descriptor_;
  metadata.reflection = ClientInput_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
