// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common/proto/udpgame.proto

#ifndef PROTOBUF_common_2fproto_2fudpgame_2eproto__INCLUDED
#define PROTOBUF_common_2fproto_2fudpgame_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_common_2fproto_2fudpgame_2eproto();
void protobuf_AssignDesc_common_2fproto_2fudpgame_2eproto();
void protobuf_ShutdownFile_common_2fproto_2fudpgame_2eproto();

class AMessage;
class Object;
class WorldState;

enum Type {
  WORLD_STATE = 1
};
bool Type_IsValid(int value);
const Type Type_MIN = WORLD_STATE;
const Type Type_MAX = WORLD_STATE;
const int Type_ARRAYSIZE = Type_MAX + 1;

const ::google::protobuf::EnumDescriptor* Type_descriptor();
inline const ::std::string& Type_Name(Type value) {
  return ::google::protobuf::internal::NameOfEnum(
    Type_descriptor(), value);
}
inline bool Type_Parse(
    const ::std::string& name, Type* value) {
  return ::google::protobuf::internal::ParseNamedEnum<Type>(
    Type_descriptor(), name, value);
}
// ===================================================================

class AMessage : public ::google::protobuf::Message {
 public:
  AMessage();
  virtual ~AMessage();
  
  AMessage(const AMessage& from);
  
  inline AMessage& operator=(const AMessage& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const AMessage& default_instance();
  
  void Swap(AMessage* other);
  
  // implements Message ----------------------------------------------
  
  AMessage* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const AMessage& from);
  void MergeFrom(const AMessage& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required .Type type = 1;
  inline bool has_type() const;
  inline void clear_type();
  static const int kTypeFieldNumber = 1;
  inline Type type() const;
  inline void set_type(Type value);
  
  // optional .WorldState world_state = 2;
  inline bool has_world_state() const;
  inline void clear_world_state();
  static const int kWorldStateFieldNumber = 2;
  inline const ::WorldState& world_state() const;
  inline ::WorldState* mutable_world_state();
  inline ::WorldState* release_world_state();
  
  // @@protoc_insertion_point(class_scope:AMessage)
 private:
  inline void set_has_type();
  inline void clear_has_type();
  inline void set_has_world_state();
  inline void clear_has_world_state();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::WorldState* world_state_;
  int type_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  friend void  protobuf_AddDesc_common_2fproto_2fudpgame_2eproto();
  friend void protobuf_AssignDesc_common_2fproto_2fudpgame_2eproto();
  friend void protobuf_ShutdownFile_common_2fproto_2fudpgame_2eproto();
  
  void InitAsDefaultInstance();
  static AMessage* default_instance_;
};
// -------------------------------------------------------------------

class Object : public ::google::protobuf::Message {
 public:
  Object();
  virtual ~Object();
  
  Object(const Object& from);
  
  inline Object& operator=(const Object& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const Object& default_instance();
  
  void Swap(Object* other);
  
  // implements Message ----------------------------------------------
  
  Object* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Object& from);
  void MergeFrom(const Object& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required float x = 1;
  inline bool has_x() const;
  inline void clear_x();
  static const int kXFieldNumber = 1;
  inline float x() const;
  inline void set_x(float value);
  
  // required float y = 2;
  inline bool has_y() const;
  inline void clear_y();
  static const int kYFieldNumber = 2;
  inline float y() const;
  inline void set_y(float value);
  
  // required float z = 3;
  inline bool has_z() const;
  inline void clear_z();
  static const int kZFieldNumber = 3;
  inline float z() const;
  inline void set_z(float value);
  
  // @@protoc_insertion_point(class_scope:Object)
 private:
  inline void set_has_x();
  inline void clear_has_x();
  inline void set_has_y();
  inline void clear_has_y();
  inline void set_has_z();
  inline void clear_has_z();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  float x_;
  float y_;
  float z_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];
  
  friend void  protobuf_AddDesc_common_2fproto_2fudpgame_2eproto();
  friend void protobuf_AssignDesc_common_2fproto_2fudpgame_2eproto();
  friend void protobuf_ShutdownFile_common_2fproto_2fudpgame_2eproto();
  
  void InitAsDefaultInstance();
  static Object* default_instance_;
};
// -------------------------------------------------------------------

class WorldState : public ::google::protobuf::Message {
 public:
  WorldState();
  virtual ~WorldState();
  
  WorldState(const WorldState& from);
  
  inline WorldState& operator=(const WorldState& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const WorldState& default_instance();
  
  void Swap(WorldState* other);
  
  // implements Message ----------------------------------------------
  
  WorldState* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const WorldState& from);
  void MergeFrom(const WorldState& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // repeated .Object object = 1;
  inline int object_size() const;
  inline void clear_object();
  static const int kObjectFieldNumber = 1;
  inline const ::Object& object(int index) const;
  inline ::Object* mutable_object(int index);
  inline ::Object* add_object();
  inline const ::google::protobuf::RepeatedPtrField< ::Object >&
      object() const;
  inline ::google::protobuf::RepeatedPtrField< ::Object >*
      mutable_object();
  
  // @@protoc_insertion_point(class_scope:WorldState)
 private:
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::RepeatedPtrField< ::Object > object_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  friend void  protobuf_AddDesc_common_2fproto_2fudpgame_2eproto();
  friend void protobuf_AssignDesc_common_2fproto_2fudpgame_2eproto();
  friend void protobuf_ShutdownFile_common_2fproto_2fudpgame_2eproto();
  
  void InitAsDefaultInstance();
  static WorldState* default_instance_;
};
// ===================================================================


// ===================================================================

// AMessage

// required .Type type = 1;
inline bool AMessage::has_type() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void AMessage::set_has_type() {
  _has_bits_[0] |= 0x00000001u;
}
inline void AMessage::clear_has_type() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void AMessage::clear_type() {
  type_ = 1;
  clear_has_type();
}
inline Type AMessage::type() const {
  return static_cast< Type >(type_);
}
inline void AMessage::set_type(Type value) {
  GOOGLE_DCHECK(Type_IsValid(value));
  set_has_type();
  type_ = value;
}

// optional .WorldState world_state = 2;
inline bool AMessage::has_world_state() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void AMessage::set_has_world_state() {
  _has_bits_[0] |= 0x00000002u;
}
inline void AMessage::clear_has_world_state() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void AMessage::clear_world_state() {
  if (world_state_ != NULL) world_state_->::WorldState::Clear();
  clear_has_world_state();
}
inline const ::WorldState& AMessage::world_state() const {
  return world_state_ != NULL ? *world_state_ : *default_instance_->world_state_;
}
inline ::WorldState* AMessage::mutable_world_state() {
  set_has_world_state();
  if (world_state_ == NULL) world_state_ = new ::WorldState;
  return world_state_;
}
inline ::WorldState* AMessage::release_world_state() {
  clear_has_world_state();
  ::WorldState* temp = world_state_;
  world_state_ = NULL;
  return temp;
}

// -------------------------------------------------------------------

// Object

// required float x = 1;
inline bool Object::has_x() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Object::set_has_x() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Object::clear_has_x() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Object::clear_x() {
  x_ = 0;
  clear_has_x();
}
inline float Object::x() const {
  return x_;
}
inline void Object::set_x(float value) {
  set_has_x();
  x_ = value;
}

// required float y = 2;
inline bool Object::has_y() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Object::set_has_y() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Object::clear_has_y() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Object::clear_y() {
  y_ = 0;
  clear_has_y();
}
inline float Object::y() const {
  return y_;
}
inline void Object::set_y(float value) {
  set_has_y();
  y_ = value;
}

// required float z = 3;
inline bool Object::has_z() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Object::set_has_z() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Object::clear_has_z() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Object::clear_z() {
  z_ = 0;
  clear_has_z();
}
inline float Object::z() const {
  return z_;
}
inline void Object::set_z(float value) {
  set_has_z();
  z_ = value;
}

// -------------------------------------------------------------------

// WorldState

// repeated .Object object = 1;
inline int WorldState::object_size() const {
  return object_.size();
}
inline void WorldState::clear_object() {
  object_.Clear();
}
inline const ::Object& WorldState::object(int index) const {
  return object_.Get(index);
}
inline ::Object* WorldState::mutable_object(int index) {
  return object_.Mutable(index);
}
inline ::Object* WorldState::add_object() {
  return object_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::Object >&
WorldState::object() const {
  return object_;
}
inline ::google::protobuf::RepeatedPtrField< ::Object >*
WorldState::mutable_object() {
  return &object_;
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {

template <>
inline const EnumDescriptor* GetEnumDescriptor< Type>() {
  return Type_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_common_2fproto_2fudpgame_2eproto__INCLUDED
